# Generated by Django 3.2.12 on 2023-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
    ]
