# Generated by Django 3.2.12 on 2023-06-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
