# Generated by Django 3.2.12 on 2023-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/store/img/user.png', upload_to='media/'),
        ),
    ]
