# Generated by Django 3.2.12 on 2023-03-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_author_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
