# Generated by Django 3.2.12 on 2023-06-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230601_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
