# Generated by Django 3.2.12 on 2023-06-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20230601_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
