# Generated by Django 3.2.12 on 2023-06-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230601_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
