# Generated by Django 3.2.12 on 2023-06-07 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_auto_20230607_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book', 'content', 'rating')},
        ),
        migrations.DeleteModel(
            name='RatingBook',
        ),
    ]
