# Generated by Django 3.2.12 on 2023-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20230607_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
